package: offlinehandler
version: '1.0.0'
author: giacomo
supportpage: github.com/giacomo/redaxo-offlinehandler

requires:
    packages:
        structure: '^2.1.0'
    redaxo: '^5.1.0'
    php:
        version: '>=5.6'
